# dispatch-spec.yaml
# 声明式工位分派规范
#
# 设计原则（033号谱系）：
#   Lead 的路由自由度通过正面规范消除，而非通过约束堵漏。
#   Lead 是 spec 解释器，不是决策者。
#   偏离 spec = 实现错误（可判定），不是设计缺陷（不可判定）。
#
# 修改路径：/ritual 仪式门控（与 definitions 同级）
# 修改提案者：meta-observer
# 版本：v1.3

version: "1.3"
provenance: "[新缠论]"
genealogy_ref: "033-declarative-dispatch-spec, 059-structural-audit"

# --- G10: structural_stations 增加 tools_required 字段 ---
structural_stations:
  - name: genealogist
    agent: ".claude/agents/genealogist.md"
    purpose: "谱系写入、张力检查、回溯扫描、结晶检测与执行、pattern-buffer 扫描（051号 Pull 模型）"
    spawn_phase: "post-definition-load"
    mandatory: true
    can_be_skipped: false
    tools_required: ["Read", "Write", "Grep", "Glob", "Task", "TaskCreate", "TaskUpdate", "TaskList", "TaskGet", "SendMessage"]

  - name: quality-guard
    agent: ".claude/agents/quality-guard.md"
    purpose: "结果包检查、代码违规扫描"
    spawn_phase: "post-definition-load"
    mandatory: true
    can_be_skipped: false
    tools_required: ["Read", "Write", "Grep", "Glob", "Task", "TaskCreate", "TaskUpdate", "TaskList", "TaskGet", "SendMessage"]

  - name: meta-observer
    agent: ".claude/agents/meta-observer.md"
    purpose: "二阶反馈回路、元编排进化、dispatch-spec 修改提案"
    spawn_phase: "post-definition-load"
    mandatory: true
    can_be_skipped: false
    tools_required: ["Read", "Write", "Grep", "Glob", "Task", "TaskCreate", "TaskUpdate", "TaskList", "TaskGet", "SendMessage"]

# --- G1: optional_stations（按需激活的结构工位） ---
optional_stations:
  - name: source-auditor
    agent: ".claude/agents/source-auditor.md"
    purpose: "溯源标签验证、引用准确性检查"
    activation_condition: "session 涉及外部文献引用或 PDF 加载"

  - name: topology-manager
    agent: ".claude/agents/topology-manager.md"
    purpose: "谱系拓扑分析、hub 节点监控、链路健康检查"
    activation_condition: "谱系总数 > 30 或 pending 谱系 > 5"

  - name: gemini-challenger
    agent: ".claude/agents/gemini-challenger.md"
    purpose: "异质否定源 + 编排者代理（030a/041号谱系）"
    activation_condition:
      - trigger: "challenge"
        condition: "definition-lawyer 提交新定义到 .chanlun/definitions/ 后自动触发异质质询"
        mode: "challenge"
      - trigger: "verify"
        condition: "spec/theorems/ 下文件发生变更时自动触发数学验证"
        mode: "verify"
      - trigger: "derive"
        condition: "定理状态变为 settled 时自动触发推论生成"
        mode: "derive"
      - trigger: "decide"
        condition: "系统遇到选择/语法记录类决断时"
        mode: "decide"
      - trigger: "manual"
        condition: "定义处于生成态且同质质询已完成 2 轮以上，由 lead 手动指定质询目标"
        mode: "challenge"

  - name: skill-crystallizer
    agent: ".claude/agents/skill-crystallizer.md"
    purpose: "pattern-buffer 达标模式结晶为 skill（043号谱系）"
    activation_condition: "pattern-buffer 中存在 status=candidate 且 frequency >= promotion_threshold 的模式"

# --- 041: orchestrator_proxy（编排者代理） ---
orchestrator_proxy:
  enabled: true
  genealogy_ref: "041-orchestrator-proxy"
  agent: ".claude/agents/gemini-challenger.md"
  mode: "decide"
  routes:
    - type: "选择"
      action: "调用 Gemini decide()，决策直接执行"
    - type: "语法记录"
      action: "调用 Gemini decide()，辨认结果写入谱系"
  human_override: "INTERRUPT — 人类编排者可随时覆盖"
  fallback: "Gemini 不可用时，写入 pending 等待人类"

# --- 037: recursive_spawning（递归蜂群分形结构） ---
recursive_spawning:
  enabled: true
  genealogy_ref: "037-recursive-swarm-fractal"
  rules:
    - "任何 teammate 面对 ≥1 个可分解子任务时，可 spawn 子 teammates"
    - "子 teammates 加入同一 team（team_name 参数）"
    - "子 teammates 使用 bypassPermissions 模式"
    - "子 teammates 继承完整的 spawn 能力——可以继续 spawn 子子 teammates（无限递归）"
    - "递归深度无人为限制，由 topology-manager 的背驰+分型信号自然终止"
    - "G8 递归适用：任何层级的子任务都不豁免蜂群"
    - "父 teammate 对子 teammates 负路由责任（收汇报、汇总结果）"
  visibility: "所有 teammates（含任意深度的子 teammates）在同一 task list 中可见"
  cost_control: "topology-manager 监控总 teammate 数量，通过背驰+分型信号判断收缩时机（非固定阈值）"

task_stations:
  derivation: "session.interruption_points + CLAUDE.md.objectives"
  spawn_phase: "post-structural-spawn"
  rules:
    - "每个独立中断点 = 一个工位（并行默认）"
    - "有数据依赖的中断点 = 串行链"
    - "Lead 不自行执行任务，只分派和汇总"
    - "无简单任务豁免——≥1 个任务即拉蜂群（bias-single-agent-bypass）"  # G8
    - "蜂群递归是默认执行模式，不是复杂度触发的优化——任何多目标任务默认并行spawn"  # 055号
    - "020号（背驰+分型）是递归的终止/结算条件，不是启动条件"
    - "子工位为局部作用域（不修改全局 hook/谱系/定义），递归深度由 topology-manager 收敛信号终止（020号背驰+分型），无人为硬限制"
    - "结构工位（genealogist/quality-guard/meta-observer）默认扁平——裁判不参与走势。例外：当结构工位自身任务需要分解时，允许 spawn 同类型子工位（受限递归），但不允许 spawn 任务工位"

# --- 059号谱系：ceremony 协议重构 ---
# 设计原则（058号定理）：
#   ceremony 是 Swarm₀，不是前置阶段。
#   无中间输出——静默扫描→内部推导→递归或终止。
#   中间报告触发 LLM 对话让步惯性（027号同构）。
#   唯一合法输出点：phase_3 的行动声明或终止声明。
ceremony_sequence:
  cold_start:
    phase_1_scan:
      description: "并行静默读取，不产出任何面向用户的输出"
      parallel: true
      steps:
        - id: "scan-definitions"
          action: "扫描 .chanlun/definitions/*.md 版本和状态"
        - id: "scan-genealogy"
          action: "扫描 .chanlun/genealogy/{pending,settled}/ 统计"
        - id: "scan-methodology"
          action: "读取 CLAUDE.md + dispatch-spec.yaml"
        - id: "scan-skills"
          action: "扫描 .chanlun/manifest.yaml skill 时间戳"
          genealogy_ref: "051-runtime-connection-design"
    phase_2_derive:
      description: "内部计算，不产出面向用户的输出"
      steps:
        - id: "derive-work"
          action: "从目标+谱系状态+代码库扫描推导任务工位"
          scan_sources:
            - "CLAUDE.md 目标"
            - "pending 谱系（生成态矛盾）"
            - "测试失败（新增 vs pre-existing）"
            - "谱系下游行动未执行（spec-execution gap）"
            - "pattern-buffer 达标模式"
          no_work_fallback: "扫描 TODO/覆盖率/spec合规/谱系张力，产出至少一个工位"
        - id: "derive-structural"
          action: "确定需要 spawn 的结构工位（mandatory 全部 spawn）"
    phase_3_recurse:
      description: "唯一输出点——行动声明或终止声明"
      steps:
        - id: "spawn-all"
          action: "并行 spawn 结构工位+任务工位"
          validation: "spawn 数量 >= structural_stations(mandatory).length"
        - id: "divine-madness"
          action: "Lead 权限剥夺（032号谱系）"
          depends_on: "spawn-all"
        - id: "recurse"
          action: "输出 '→ 接下来：[action]' 紧跟 tool 调用"
          depends_on: "divine-madness"
      terminate_condition:
        trigger: "derive-work 扫描全部来源后仍无工位可派生"
        action: "输出 '[020号反转] 无新区分可产出——系统干净终止' → 停止"
        note: "这是唯一合法的 ceremony 终止路径"

  warm_start:
    phase_1_scan:
      description: "并行静默读取，不产出面向用户的输出"
      parallel: true
      steps:
        - id: "locate-session"
          action: "定位最新 .chanlun/sessions/*.md"
        - id: "scan-definitions"
          action: "扫描当前 definitions/ 版本"
        - id: "scan-genealogy"
          action: "扫描当前 genealogy/ 状态"
    phase_2_derive:
      description: "内部计算，不产出面向用户的输出"
      steps:
        - id: "version-diff"
          action: "对比 session vs 当前定义版本（内部，不输出报告）"
        - id: "genealogy-diff"
          action: "对比 session vs 当前谱系状态（内部，不输出报告）"
        - id: "derive-work"
          action: "从中断点+差异+代码库扫描推导任务工位"
          scan_sources:
            - "session 中断点"
            - "version-diff 中的升级/新增项"
            - "genealogy-diff 中的新 pending"
            - "测试失败（新增 vs pre-existing）"
            - "谱系下游行动未执行（spec-execution gap）"
            - "pattern-buffer 达标模式"
          no_work_fallback: "扫描 TODO/覆盖率/spec合规/谱系张力，产出至少一个工位"
    phase_3_recurse:
      description: "唯一输出点——行动声明或终止声明（同 cold_start）"
      steps:
        - id: "spawn-all"
          action: "并行 spawn 结构工位+任务工位"
          validation: "spawn 数量 >= structural_stations(mandatory).length"
        - id: "divine-madness"
          action: "Lead 权限剥夺（032号谱系）"
          depends_on: "spawn-all"
        - id: "recurse"
          action: "输出 '→ 接下来：[action]' 紧跟 tool 调用"
          depends_on: "divine-madness"
      terminate_condition:
        trigger: "derive-work 扫描全部来源后仍无工位可派生"
        action: "输出 '[020号反转] 无新区分可产出——系统干净终止' → 停止"

validation:
  post_ceremony:
    - check: "all_structural_spawned"
      condition: "所有 structural_stations 中 mandatory=true 的工位均已 spawn"
      on_fail: "阻塞——不允许进入蜂群循环"
    - check: "lead_permissions_restricted"
      condition: "settings.local.json 中 Lead 只保留 Read/Glob/Grep/Task/SendMessage/TaskList/TaskGet/TaskUpdate"
      on_fail: "阻塞——032号谱系要求"
    - check: "task_stations_derived"
      condition: "至少从中断点派生了一个任务工位（除非中断点为空）"
      on_fail: "警告——可能遗漏工作"
    # G2: crystallization_check
    - check: "crystallization_check"
      condition: "genealogist 的结晶检测已执行（扫描近期谱系的背驰+分型信号）"
      on_fail: "警告——可能遗漏结晶时机"
    # G6: 构成性矛盾记录（不修 spec，注释记录）
    # 注意：meta-observer 自身是 dispatch-spec 的修改提案者，同时也是 dispatch-spec 的执行监控者。
    # 这是构成性矛盾（020号谱系）：观察者与被观察系统不可分离。
    # 处置：接受为系统的构成性特征，meta-observer 持续监控此矛盾的表现。

  # G4: post_commit_flow 引用
  post_commit:
    ref: ".claude/skills/meta-orchestration/references/post-commit-flow.md"
    description: "commit 后执行的标准流程（session 写入、谱系更新检查）"

# G3: axis_report 模板定义
axis_report:
  template:
    sections:
      - "定义基底状态（新增/修改/删除）"
      - "谱系状态（pending 数量、近期结算、结晶信号）"
      - "蜂群工位状态（各工位进度摘要）"
      - "中断点消化进度"
      - "下一步行动建议"
    constraints:
      - "每个 section 不超过 3 行"
      - "只报告变化，不重复已知信息"
  frequency: "每蜂群循环结束"
  producer: "Lead"
  consumers: "所有工位（通过 broadcast 或 session 文件）"

# --- 043: automation（自生长回路基础设施） ---
automation:
  pattern_detection:
    enabled: true
    trigger: "session_end"
    buffer_path: ".chanlun/pattern-buffer.yaml"
    min_sequence_length: 2
    promotion_threshold: 3  # 频次达标阈值
  crystallization:
    auto_trigger: true
    require_genealogy_settlement: true
  manifest:
    path: ".chanlun/manifest.yaml"
    auto_register: true

# --- 049: orchestration_protocol（事件路由表） ---
orchestration_protocol:
  version: "1.0"
  genealogy_ref: "049-orchestration-routing-table"
  routes:
    - event: file_change
      pattern: "spec/theorems/*"
      target: gemini_math_verify
      action: "gemini_challenger verify --context-file {file}"
      priority: high

    - event: file_change
      pattern: "docs/chan_spec.md"
      target: genealogist
      action: "lineage_consistency_check"
      priority: high

    - event: file_create
      pattern: "**/*"
      target: manifest_guard
      action: "check_manifest_registration"
      priority: high

    - event: annotation
      pattern: "@proof-required"
      target: gemini_math_prove
      action: "gemini_challenger challenge --math"
      priority: low_async

    - event: task_queue
      condition: "independent_tasks >= 2"
      target: swarm_manager
      action: "spawn_recursive_swarm"
      priority: high

    - event: session_start
      target: meta_lead
      action: "ceremony"
      priority: critical

    - event: session_end
      target: pattern_detector
      action: "post_session_pattern_detect"
      priority: low_async

    - event: tool_error
      pattern: "gemini_api_*"
      target: system
      action: "fallback_local_rules"
      priority: critical

    - event: build_failure
      condition: "consecutive_failures >= 3"
      target: build_resolver
      action: "auto_fix_build"
      priority: medium
