#!/usr/bin/env bash
# harvest.sh - sandcastle branch auto-acceptance (#1003 orchestrator gate, scripted)
# verify -> cherry-pick -> push -> close. Red => skip+report. Pure ASCII (bash 3.2).
# git 2.50.1 notes: cherry-pick has NO -q flag; use plain cherry-pick, capture rc directly.
set -euo pipefail
REPO=/Users/silencehan/Projects/NewChanlun
WT=/tmp/harvest
SKIP_ISSUES="${SKIP_ISSUES:-1024 1025}"

cd "$REPO"
git fetch origin main -q
if ! git -C "$WT" rev-parse --git-dir >/dev/null 2>&1; then git worktree add -q "$WT" main; fi
git -C "$WT" fetch -q origin main
git -C "$WT" reset -q --hard origin/main

harvested=0
failed=0
for br in $(git branch --list 'sandcastle/issue-*' --format='%(refname:short)' | sort -t- -k3 -n); do
  n="${br##*-}"
  if [[ " $SKIP_ISSUES " == *" $n "* ]]; then echo "SKIP $br (skip-list)"; continue; fi
  st=$(gh issue view "$n" --json state --jq .state 2>/dev/null) || true
  if [ -z "$st" ]; then echo "SKIP $br (state read failed, retry later)"; continue; fi
  if [ "$st" = "CLOSED" ]; then git branch -qD "$br" >/dev/null 2>&1 || true; continue; fi
  if git merge-base --is-ancestor "$br" origin/main 2>/dev/null; then
    git branch -qD "$br" >/dev/null 2>&1 || true; continue
  fi
  shas=$(git rev-list --reverse origin/main.."$br")
  if [ -z "$shas" ]; then echo "SKIP $br (no new commits)"; continue; fi
  ok=1
  for sha in $shas; do
    git -C "$WT" cherry-pick "$sha" >/dev/null 2>&1 || true
    rc=$?
    if [ $rc != 0 ]; then
      if git -C "$WT" diff --cached --quiet 2>/dev/null; then
        git -C "$WT" cherry-pick --skip >/dev/null 2>&1 || git -C "$WT" reset -q --hard HEAD
      else
        git -C "$WT" cherry-pick --abort >/dev/null 2>&1 || true
        echo "FAIL $br (cherry-pick $sha)"; ok=0; break
      fi
    fi
  done
  if [ $ok = 1 ] && ! (cd "$WT/rust" && CARGO_TARGET_DIR=/tmp/harvest-t cargo test --lib >/dev/null 2>&1); then echo "FAIL $br (lib tests red)"; ok=0; fi
  if [ $ok = 1 ] && ! (cd "$WT/rust" && CARGO_TARGET_DIR=/tmp/harvest-t cargo fmt --check >/dev/null 2>&1); then echo "FAIL $br (fmt drift)"; ok=0; fi
  if [ $ok = 1 ] && ! (cd "$WT/rust" && CARGO_TARGET_DIR=/tmp/harvest-t cargo check --all-targets >/dev/null 2>&1); then echo "FAIL $br (check red)"; ok=0; fi
  if [ $ok = 1 ] && ! (cd "$WT/rust" && CARGO_TARGET_DIR=/tmp/harvest-t cargo check --all-targets --features backtest_bin >/dev/null 2>&1); then echo "FAIL $br (backtest_bin check red)"; ok=0; fi
  if [ $ok = 1 ] && ! git -C "$WT" push -q origin main:main; then echo "FAIL $br (push)"; ok=0; fi
  if [ $ok = 1 ] && ! git merge-base --is-ancestor "$br" origin/main 2>/dev/null; then
    echo "FAIL $br (post-push ancestor check: branch not in origin/main, will NOT close ticket)"; ok=0
  fi
  if [ $ok = 1 ]; then
    flat=$(echo $shas | tr '\n' ' ')
    comment_done=0
    for attempt in 1 2 3; do
      gh issue comment "$n" --body "> *This was generated by AI during wayfinding.*

**Auto-accept (harvest.sh, #1003 gate scripted)**: sandcastle two-phase branch $br green (lib full / fmt / check both feature sets); commits $flat merged and pushed to main." >/dev/null && { comment_done=1; break; }
      sleep 5
    done
    [ $comment_done = 1 ] || echo "WARN $br (comment failed 3x, closing anyway)"
    gh issue close "$n" >/dev/null
    echo "HARVESTED $br -> main"
    harvested=$((harvested+1))
    git branch -qD "$br" >/dev/null 2>&1 || true
  else
    failed=$((failed+1))
    git -C "$WT" reset -q --hard origin/main
  fi
done
echo "harvest done: harvested=$harvested failed=$failed"
